site_name: Billy Hughes

nav:
- 'Home': 'index.md'
- 'Text Editor Extensions': 'text_ed.md'
- 'Useful MAGIC/CS Tips':
  - 'Printing data structures': 'magic_tips/data_structures.md'
  - 'Debugging': 'magic_tips/debugging.md'
  - 'Miscellaneous': 'magic_tips/misc.md'

theme:
  name: material
  highlightjs: false

extra_css:
  - 'extra.css'
